spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:192.168.113.129}:${DB_PORT:5432}/${DB_NAME:employee_manager}
    username: ${DB_USERNAME:app}
    password: ${DB_PASSWORD:app123456}
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      pool-name: employee-manager-pool
      connection-timeout: 3000

logging:
  level:
    root: warn
    com.aidigital.employee: info
